### ISSUE TITLE
Dropping packages doesn't remove signatures

### ISSUE THREAD

**Issue by Celti** [vodik/repose#37]
Follow-up to #31 and #36, after dropping a package the link to the .sig still remains. I completely forgot to add signatures to unlink_pkg, not just symlink_pkg and clone_pkg!

**Comment by vodik** [comment]
Ha, you're right. Didn't think to try that. Note to self: work on testing too.

**Comment by vodik** [comment]
@Celti mind giving this a test? I don't happen to have repository on hand with signatures at the moment. But it *should* do the trick.

**Comment by Celti** [comment]
Yep, that works just fine! Thanks for the quick turnaround!

**Comment by vodik** [comment]
Thanks again!
