### ISSUE TITLE
Create empty db

### ISSUE THREAD

**Issue by mkoskar** [vodik/repose#39]
If database doesn't exist it is only created "lazily" when adding some package/s to it.
It would be nice if (when running in "add mode") it is always created even though it might be empty.

This would streamline initialization of repository (which might be empty) without need to resort to `repo-add` or creating empty archive manually.

**Comment by vodik** [comment]
I think this is a great idea.

**Comment by vodik** [comment]
Opened a PR just because I want to field an opinion on this. Should it always happen (I think it should), or be hidden behind a flag. I can't think of any corner cases I'm breaking, but its worth fielding the question.

Any opinion

**Comment by kyrias** [comment]
My initial feeling is that it would make more sense to have it behind a flag so you don't end up with a bunch of empty DBs by accident, but when actually thinking about it I can't really think of any reason not to have it always happen, so I guess I'm in favor of it?

**Comment by vodik** [comment]
Yeah, and tar behaves the same way - you can create an empty an empty tar archive.

I see both repose and pacman as nothing more than glorified tar implementations, so I think its reasonable to match that behaviour.

**Comment by mkoskar** [comment]
I see the #40 claims it was merged to `master`, yet it's not to be found there, `git push --force` maybe?

**Comment by vodik** [comment]
Double checking... huh

**Comment by vodik** [comment]
Grrrr, you're right, I screwed up the 6.1 release and I lost too commits in the process. Thank you reflog.

**Comment by vodik** [comment]
Okay, released 6.2 and restored the lost commits.
